config/routes.rb
Rails.application.routes.draw do
  resources :cats, :only => [:create, :destroy, :index, :show, :update, :new, :edit]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(blue white red yellow green)
  validates :sex, :name, :color, presence: true
  validates :color, inclusion: { in: COLORS }

  has_many(
    :cat_rental_requests,
    class_name: 'CatRentalRequest',
    primary_key: :id,
    foreign_key: :cat_id
  )

  def age
    ((Time.now - self.birth_date.to_time) / 31557600).to_i
  end

end

app/models/cat_rental_request.rb
require 'byebug'

class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: ['PENDING', 'APPROVED'] }

  belongs_to(
    :cat,
    class_name: 'Cat',
    primary_key: :id,
    foreign_key: :cat_id
  )

  def overlapping_requests
    @cat = cat
    old_date = 0
    @cat.cat_rental_requests
    # @cat.cat_rental_requests.each do |request|
    #   end_date = request.end_date
    #   start_date = request.start_date
    # end
  end

  def overlapping_approved_requests

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      @error = @cat.errors.full_messages
      render :error
    end
  end

  def edit
    @cat = Cat.find(params[:id])

    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat
      @cat.update(cat_params)
    end
    render :show
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action_url = (@cat.persisted? ? cat_url(@cat) : cats_url) %>
<br>
<form  action="<%= action_url %>" method="post">
  <% if @cat.persisted? %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  Name: <input type='text' name='cat[name]' value="<%= @cat.name %>">
  <br>
  <%
    if @cat.sex == 'M'
      male_checked = "checked"
    else
      female_checked = "checked"
    end
  %>
  <input type='radio' name='cat[sex]' value='M' <%= male_checked %> > Male
  <br>
  <input type='radio' name='cat[sex]' value='F' <%= female_checked %>> Female
  <br>

  <% @cat.color %>
  <select name="cat[color]">
    <option>Pick a Color</option>

    <% Cat::COLORS.each do |color| %>
    <option
      value="<%= color.downcase %>"
      <%= "selected if @cat.color == color" %>>
      <%= color.capitalize %>
    </option>
    <% end %>

  </select>
  <br>
  Cat's Birthday: <input value="<%= @cat.birth_date %>" type="date" name="cat[birth_date]">
  <br>
  Description:
  <textarea name="cat[description]"> <%= @cat.description %> </textarea>
  <br>
  <input type="submit" value="Submit"/>
</form>

app/views/cats/edit.html.erb
<h1>Edit Your Cat</h1>
<%= render partial: "form" %>

<!-- <br>
<form  action="/cats" method="get">
  <input type="hidden" name="_method" value="patch">
  Name: <input type='text' name='cat[name]' value="<%= @cat.name %>">
  <br>
  <%
    if @cat.sex == 'M'
      male_checked = "checked"
    else
      female_checked = "checked"
    end
  %>
  <input type='radio' name='cat[sex]' value='M' <%= male_checked %> > Male
  <br>
  <input type='radio' name='cat[sex]' value='F' <%= female_checked %>> Female
  <br>
  <%= red_selected = "selected" if @cat.color == 'red'
      blue_selected = "selected" if @cat.color == 'blue'
      green_selected = "selected" if @cat.color == 'green'
      white_selected = "selected" if @cat.color == 'white'
      yellow_selected = "selected" if @cat.color == 'yellow'%>
  <% @cat.color %>
  <select name="cat[color]">
    <option>Pick a Color</option>
    <option <%=red_selected%> value="red">Red</option>
    <option <%=blue_selected%> value="blue">Blue</option>
    <option <%=green_selected%> value="green">Green</option>
    <option <%=white_selected%> value="white">White</option>
    <option <%=yellow_selected%> value="yellow">Yellow</option>
  </select>
  <br>
  Cat's Birthday: <input value="<%= @cat.birth_date %>" type="date" name="cat[birth_date]">
  <br>
  Description:
  <textarea name="cat[description]"> <%= @cat.description %> </textarea>
  <br>
  <input type="submit" value="Submit"/>
</form> -->

app/views/cats/error.html.erb
<ul>
  <% @error.each do |err|  %>
    <li><%= err %></li>
  <% end %>
</ul>

app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat| %>
    <li>
      <a href="<%= cat_url(cat) %>"> <%= cat.name %> </a>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<%= render "form" %>

<!-- <form  action="/cats" method="post">
  Name: <input type='text' name='cat[name]'>
  <br>
  <input type='radio' name='cat[sex]' value='M'> Male
  <br>
  <input type='radio' name='cat[sex]' value='F'> Female
  <br>
  <select name="cat[color]">
    <option>Pick a Color</option>
    <option value="red">Red</option>
    <option value="blue">Blue</option>
    <option value="green">Green</option>
    <option value="white">White</option>
    <option value="yellow">Yellow</option>
  </select>
  <br>
  Cat's Birthday: <input type="date" name="cat[birth_date]">
  <br>
  Description:
  <textarea name="cat[description]"></textarea>
  <br>
  <input type="submit" value="Submit"/>
</form> -->

app/views/cats/show.html.erb
<table>
  <tr>
    <% @cat.attributes.keys[0..-3].each do |attribute| %>
      <th> <%= attribute %></th>
    <% end %>
  </tr>
  <tr>
    <% @cat.attributes.values[0..-3].each do |value| %>
      <td> <%= value %></td>
    <% end %>
  </tr>
</table>

app/views/cats/update.html.erb
<h1>Updated</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>